### ISSUE TITLE
variable i not declared

### ISSUE THREAD

**Issue by MageCoder** [beaups/giulia_ESCape#1]
https://github.com/beaups/giulia_ESCape/blob/fec52e9da8421ea4ccedd25aba27ade66326d54d/ESCaped.ino#L52

Please add 
int i = 0;
in front of while loop.

**Comment by beaups** [comment]
Thanks, I meant to remove all the Serial.print() and missed those.

**Comment by beaups** [comment]
Just checked my local code, and funny enough that declaration is in there.  Must have pushed prior to save.  Thanks
